-- CREATE SCHEMA "vikings";

CREATE TABLE "vikings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "viking_movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "viking_id" integer UNIQUE,
  "name" varchar NOT NULL,
  "actor_name" varchar,
  "description" varchar,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "viking_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "viking_id" integer,
  "movie_id" integer,
  "image_url" varchar NOT NULL,
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "viking_movies" ADD FOREIGN KEY ("viking_id") REFERENCES "vikings" ("id");

ALTER TABLE "viking_images" ADD FOREIGN KEY ("movie_id") REFERENCES "viking_movies" ("id");

ALTER TABLE "viking_images" ADD FOREIGN KEY ("viking_id") REFERENCES "vikings" ("id");
